# Generated by Django 3.0.2 on 2020-01-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4Y03vu_-s0Hm8NJbdVxFkVFH5Rhi9STNfuz2-PwckMnj5p768&s', max_length=500),
        ),
    ]
